apiVersion: v1
kind: Service
metadata:
  name: chaoscoordinatorsvc
  labels:
    run: chaoscoordinatorservice
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
  selector:
    run: chaoscoordinatorservice

